/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';


export namespace Components {

  interface ProductComponent {}
  interface ProductComponentAttributes extends StencilHTMLAttributes {}

  interface ProductDetails {}
  interface ProductDetailsAttributes extends StencilHTMLAttributes {}

  interface ProductList {}
  interface ProductListAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'ProductComponent': Components.ProductComponent;
    'ProductDetails': Components.ProductDetails;
    'ProductList': Components.ProductList;
  }

  interface StencilIntrinsicElements {
    'product-component': Components.ProductComponentAttributes;
    'product-details': Components.ProductDetailsAttributes;
    'product-list': Components.ProductListAttributes;
  }


  interface HTMLProductComponentElement extends Components.ProductComponent, HTMLStencilElement {}
  var HTMLProductComponentElement: {
    prototype: HTMLProductComponentElement;
    new (): HTMLProductComponentElement;
  };

  interface HTMLProductDetailsElement extends Components.ProductDetails, HTMLStencilElement {}
  var HTMLProductDetailsElement: {
    prototype: HTMLProductDetailsElement;
    new (): HTMLProductDetailsElement;
  };

  interface HTMLProductListElement extends Components.ProductList, HTMLStencilElement {}
  var HTMLProductListElement: {
    prototype: HTMLProductListElement;
    new (): HTMLProductListElement;
  };

  interface HTMLElementTagNameMap {
    'product-component': HTMLProductComponentElement
    'product-details': HTMLProductDetailsElement
    'product-list': HTMLProductListElement
  }

  interface ElementTagNameMap {
    'product-component': HTMLProductComponentElement;
    'product-details': HTMLProductDetailsElement;
    'product-list': HTMLProductListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
